<?php
session_start();
session_destroy();
$_SESSION['usuario']="";
$_SESSION['rol']="";
$_SESSION['nombreC']="";
$_SESSION['id']="";
$_SESSION['nombreT']="";
$_SESSION['idPersona']="";
header('location:../index.php');
?>